name: Create Dependency Tree Diagram

on:
  push:
    branches: [ master ]

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1

    - name: Build project
      run: dotnet publish -r ubuntu.14.04-x64 -o=out -p:PublishSingleFile=true -p:UseAppHost=true --self-contained
      working-directory: ./src/Pokedex

    - name: Generate UML dependencies
      id: generate_uml
      uses: maisiesadler/deptree@v0.0.30-beta001
      env:
        ASSEMBLY_LOCATION: './out/Pokedex'
        ROOT_TYPES: 'Pokedex.Controllers.PokemonController'

    - name: Output file
      shell: bash
      run: echo '${{ steps.generate_uml.outputs.result }}' > DependencyTree.md

    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'Generate diagrams'
